-- Tipos
CREATE TYPE user_status_enum AS ENUM ('ACTIVE', 'INACTIVE', 'PENDENT');
CREATE TYPE user_type_enum AS ENUM ('CLIENT', 'ENTERPRISE', 'INTERPRETER');
CREATE TYPE interpreter_modality_enum AS ENUM ('ONLINE', 'PERSONALLY', 'ALL');
CREATE TYPE appointment_modality_enum AS ENUM ('ONLINE', 'PERSONALLY');
CREATE TYPE appointment_status_enum AS ENUM ('PENDENT', 'ACCEPTED', 'CANCELED', 'COMPLETED');
CREATE TYPE schedule_day_enum AS ENUM ('MON', 'TUE', 'WEN', 'THU', 'FRI', 'SAT', 'SUN');
CREATE TYPE person_gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHERS');

-- Usuário base
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(11) NOT NULL,
  picture TEXT,
  status user_status_enum NOT NULL,
  type user_type_enum NOT NULL
);

-- Pessoa (CLIENT)
CREATE TABLE person (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  gender person_gender_enum NOT NULL,
  birthday DATE NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  CONSTRAINT fk_person_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

-- Empresa (ENTERPRISE)
CREATE TABLE enterprise (
  id BIGINT PRIMARY KEY,
  corporate_reason VARCHAR(255) NOT NULL,
  cnpj VARCHAR(14) NOT NULL UNIQUE,
  CONSTRAINT fk_enterprise_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

-- Intérprete (INTERPRETER)
CREATE TABLE interpreter (
  id BIGINT PRIMARY KEY,
  cnpj VARCHAR(14),
  rating NUMERIC NOT NULL,
  min_value DECIMAL NOT NULL,
  max_value DECIMAL NOT NULL,
  image_rights BOOLEAN NOT NULL,
  modality interpreter_modality_enum NOT NULL,
  description TEXT NOT NULL,
  CONSTRAINT fk_interpreter_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

-- Especialidades
CREATE TABLE specialties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE user_specialties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specialtie_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_user_specialties_specialtie FOREIGN KEY (specialtie_id) REFERENCES specialties (id),
  CONSTRAINT fk_user_specialties_user       FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Agendamento
CREATE TABLE appointment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UF VARCHAR(2) NOT NULL,
  city VARCHAR(255) NOT NULL,
  modality appointment_modality_enum NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  status appointment_status_enum NOT NULL,
  interpreter_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  CONSTRAINT fk_appointment_interpreter FOREIGN KEY (interpreter_id) REFERENCES interpreter (id),
  CONSTRAINT fk_appointment_user        FOREIGN KEY (user_id)        REFERENCES users (id)
);

-- Avaliação
CREATE TABLE rating (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stars DECIMAL NOT NULL,
  description TEXT,
  appointment_id BIGINT NOT NULL,
  CONSTRAINT fk_rating_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (id)
);

-- Agenda intérprete
CREATE TABLE schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interpreter_id BIGINT NOT NULL,
  day schedule_day_enum NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  CONSTRAINT fk_schedule_interpreter FOREIGN KEY (interpreter_id) REFERENCES interpreter (id)
);

-- Parâmetros gerais
CREATE TABLE parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL,
  value TEXT NOT NULL
);

-- Documentos do intérprete
CREATE TABLE interpreter_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interpreter_id BIGINT NOT NULL,
  document TEXT NOT NULL,
  CONSTRAINT fk_documents_interpreter FOREIGN KEY (interpreter_id) REFERENCES interpreter (id)
);

-- Localização do usuário
CREATE TABLE location (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UF VARCHAR(2),
  city VARCHAR(255),
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_location_user FOREIGN KEY (user_id) REFERENCES users (id)
);
