-- Create points table for time tracking
CREATE TABLE points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    description VARCHAR(255),
    timestamp TIMESTAMP NOT NULL,
    type VARCHAR(50) NOT NULL,
    CONSTRAINT fk_points_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Add index on user_id for faster queries
CREATE INDEX idx_points_user_id ON points(user_id);

-- Add index on timestamp for faster time-based queries
CREATE INDEX idx_points_timestamp ON points(timestamp);
