name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Subir serviços com Docker Compose
        run: |
          docker-compose -f ./pointtils/docker-compose.yaml up --build -d
          docker-compose -f ./pointtils/docker-compose.yaml ps
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_APPLICATION_NAME: ${{ vars.SPRING_APPLICATION_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          SPRING_JPA_SHOW_SQL: ${{ vars.SPRING_JPA_SHOW_SQL }}
          SPRINGDOC_API_DOCS_ENABLED: ${{ vars.SPRINGDOC_API_DOCS_ENABLED }}
          SPRINGDOC_SWAGGER_UI_ENABLED: ${{ vars.SPRINGDOC_SWAGGER_UI_ENABLED }}
          SPRINGDOC_SWAGGER_UI_PATH: ${{ vars.SPRINGDOC_SWAGGER_UI_PATH }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Esperar serviços ficarem disponíveis
        run: sleep 30

      - name: Executar testes
        run: mvn test
        working-directory: ./pointtils


      - name: Derrubar serviços do Docker Compose
        run: docker-compose -f ./pointtils/docker-compose.yaml down