name: Mirror to AGES GitLab

on:
  push:
    branches: ["main"] # Altere se usar outro branch principal
  workflow_dispatch: # Permite acionar manualmente

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para histórico completo

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to AGES GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@tools.ages.pucrs.br/point-tils-um-aplicativo-para-interpretes-de-lingua-brasileira-de-sinais/backend.git
          git push --mirror gitlab
