name: Mirror to AGES GitLab (HTTPS)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Test Network Connectivity
        run: |
          echo "=== Network Diagnostics ==="
          echo "Testing basic connectivity..."
          ping -c 3 tools.ages.pucrs.br || echo "Ping failed"
          
          echo "Testing DNS resolution..."
          nslookup tools.ages.pucrs.br || echo "DNS lookup failed"
          
          echo "Testing HTTPS connectivity..."
          curl -I https://tools.ages.pucrs.br || echo "HTTPS connection failed"

      - name: Remove existing remote (if exists)
        run: |
          git remote remove gitlab || true

      - name: Add GitLab remote (HTTPS)
        run: |
          git remote add gitlab https://tools.ages.pucrs.br/point-tils-um-aplicativo-para-interpretes-de-lingua-brasileira-de-sinais/backend.git
          git remote -v

      - name: Mirror Repository (HTTPS)
        run: |
          echo "Starting mirror push via HTTPS..."
          git push --mirror gitlab
          echo "Mirror completed successfully"
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
