name: Mirror to AGES GitLab (SSH)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host tools.ages.pucrs.br\n  Port 8822\n  User git\n  IdentityFile ~/.ssh/id_rsa\n  ServerAliveInterval 15" >> ~/.ssh/config
          ssh-keyscan -p 8822 -t rsa tools.ages.pucrs.br >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -T git@tools.ages.pucrs.br -p 8822 || true

      - name: Mirror Repository
        run: |
          git remote add gitlab ssh://git@tools.ages.pucrs.br:8822/point-tils-um-aplicativo-para-interpretes-de-lingua-brasileira-de-sinais/backend.git
          git push --mirror gitlab
