name: Notify Sprint Deadlines

on:
  schedule:
    - cron: "0 08 * * *"
  workflow_dispatch:

concurrency:
  group: notify-deadlines
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install requests

      - name: Run deadline checker
        env:
          DEADLINE_TOKEN: ${{ secrets.DEADLINE_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_DEADLINE_WEBHOOK }}
          DISCORD_USERS: ${{ secrets.DISCORD_USERS }}
          GITHUB_ORG: PointTils
          PROJECT_NUMBER: 4
        run: python scripts/check_deadlines.py
